# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenxinye/Desktop/TESTSNN/cABBA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenxinye/Desktop/TESTSNN/cABBA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenxinye/Desktop/TESTSNN/cABBA/CMakeFiles /home/chenxinye/Desktop/TESTSNN/cABBA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenxinye/Desktop/TESTSNN/cABBA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ABBA

# Build rule for target.
ABBA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ABBA
.PHONY : ABBA

# fast build rule for target.
ABBA/fast:
	$(MAKE) -f CMakeFiles/ABBA.dir/build.make CMakeFiles/ABBA.dir/build
.PHONY : ABBA/fast

#=============================================================================
# Target rules for targets named abba

# Build rule for target.
abba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abba
.PHONY : abba

# fast build rule for target.
abba/fast:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/build
.PHONY : abba/fast

runtest.o: runtest.cpp.o

.PHONY : runtest.o

# target to build an object file
runtest.cpp.o:
	$(MAKE) -f CMakeFiles/ABBA.dir/build.make CMakeFiles/ABBA.dir/runtest.cpp.o
.PHONY : runtest.cpp.o

runtest.i: runtest.cpp.i

.PHONY : runtest.i

# target to preprocess a source file
runtest.cpp.i:
	$(MAKE) -f CMakeFiles/ABBA.dir/build.make CMakeFiles/ABBA.dir/runtest.cpp.i
.PHONY : runtest.cpp.i

runtest.s: runtest.cpp.s

.PHONY : runtest.s

# target to generate assembly for a file
runtest.cpp.s:
	$(MAKE) -f CMakeFiles/ABBA.dir/build.make CMakeFiles/ABBA.dir/runtest.cpp.s
.PHONY : runtest.cpp.s

src/ABBA.o: src/ABBA.cpp.o

.PHONY : src/ABBA.o

# target to build an object file
src/ABBA.cpp.o:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/ABBA.cpp.o
.PHONY : src/ABBA.cpp.o

src/ABBA.i: src/ABBA.cpp.i

.PHONY : src/ABBA.i

# target to preprocess a source file
src/ABBA.cpp.i:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/ABBA.cpp.i
.PHONY : src/ABBA.cpp.i

src/ABBA.s: src/ABBA.cpp.s

.PHONY : src/ABBA.s

# target to generate assembly for a file
src/ABBA.cpp.s:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/ABBA.cpp.s
.PHONY : src/ABBA.cpp.s

src/compress.o: src/compress.cpp.o

.PHONY : src/compress.o

# target to build an object file
src/compress.cpp.o:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/compress.cpp.o
.PHONY : src/compress.cpp.o

src/compress.i: src/compress.cpp.i

.PHONY : src/compress.i

# target to preprocess a source file
src/compress.cpp.i:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/compress.cpp.i
.PHONY : src/compress.cpp.i

src/compress.s: src/compress.cpp.s

.PHONY : src/compress.s

# target to generate assembly for a file
src/compress.cpp.s:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/compress.cpp.s
.PHONY : src/compress.cpp.s

src/digitization.o: src/digitization.cpp.o

.PHONY : src/digitization.o

# target to build an object file
src/digitization.cpp.o:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/digitization.cpp.o
.PHONY : src/digitization.cpp.o

src/digitization.i: src/digitization.cpp.i

.PHONY : src/digitization.i

# target to preprocess a source file
src/digitization.cpp.i:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/digitization.cpp.i
.PHONY : src/digitization.cpp.i

src/digitization.s: src/digitization.cpp.s

.PHONY : src/digitization.s

# target to generate assembly for a file
src/digitization.cpp.s:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/digitization.cpp.s
.PHONY : src/digitization.cpp.s

src/global_func.o: src/global_func.cpp.o

.PHONY : src/global_func.o

# target to build an object file
src/global_func.cpp.o:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/global_func.cpp.o
.PHONY : src/global_func.cpp.o

src/global_func.i: src/global_func.cpp.i

.PHONY : src/global_func.i

# target to preprocess a source file
src/global_func.cpp.i:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/global_func.cpp.i
.PHONY : src/global_func.cpp.i

src/global_func.s: src/global_func.cpp.s

.PHONY : src/global_func.s

# target to generate assembly for a file
src/global_func.cpp.s:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/global_func.cpp.s
.PHONY : src/global_func.cpp.s

src/operator_loader.o: src/operator_loader.cpp.o

.PHONY : src/operator_loader.o

# target to build an object file
src/operator_loader.cpp.o:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/operator_loader.cpp.o
.PHONY : src/operator_loader.cpp.o

src/operator_loader.i: src/operator_loader.cpp.i

.PHONY : src/operator_loader.i

# target to preprocess a source file
src/operator_loader.cpp.i:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/operator_loader.cpp.i
.PHONY : src/operator_loader.cpp.i

src/operator_loader.s: src/operator_loader.cpp.s

.PHONY : src/operator_loader.s

# target to generate assembly for a file
src/operator_loader.cpp.s:
	$(MAKE) -f CMakeFiles/abba.dir/build.make CMakeFiles/abba.dir/src/operator_loader.cpp.s
.PHONY : src/operator_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ABBA"
	@echo "... abba"
	@echo "... runtest.o"
	@echo "... runtest.i"
	@echo "... runtest.s"
	@echo "... src/ABBA.o"
	@echo "... src/ABBA.i"
	@echo "... src/ABBA.s"
	@echo "... src/compress.o"
	@echo "... src/compress.i"
	@echo "... src/compress.s"
	@echo "... src/digitization.o"
	@echo "... src/digitization.i"
	@echo "... src/digitization.s"
	@echo "... src/global_func.o"
	@echo "... src/global_func.i"
	@echo "... src/global_func.s"
	@echo "... src/operator_loader.o"
	@echo "... src/operator_loader.i"
	@echo "... src/operator_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

