name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        rm -rf CMakeCache.txt CMakeFiles
        sudo apt-get install cmake 
        sudo apt-get install build-essential
        cmake .
        make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
